stages:
  - test

rust:deny:
  stage: test
  image: rust:1.84-alpine3.21
  before_script:
    - apk add cargo-deny
  script:
    - cargo deny check

rust:fmt:
  stage: test
  image: rust:1.84-alpine3.21
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

rust:clippy:
  stage: test
  image: rust:1.84-alpine3.20
  before_script:
    - apk add build-base musl-dev linux-headers cmake perl go
    - rustup component add clippy
  script:
    - cargo clippy --all-features -- -D warnings

rust:hack:
  stage: test
  image: rust:1.84-alpine3.20
  before_script:
    - apk add build-base musl-dev linux-headers cmake perl go
    - cargo install --locked cargo-hack@0.6.34
  script:
    - cargo hack check --feature-powerset --no-dev-deps --at-least-one-of aws-lc-rs,ring

rust:test:
  stage: test
  image: rust:1.84-alpine3.21
  before_script:
    - apk add musl-dev cmake perl go
  script:
    - cargo test
    - cargo test --features websocket,portable-atomic
    - cargo test --no-default-features --features ring
